#pragma once

/*
    AUv3 Audio Unit Wrapper

    Copyright (c) 2024 Timo Kaluza (defiantnerd)

    This file is part of the clap-wrappers project which is released under MIT License.
    See file LICENSE or go to https://github.com/free-audio/clap-wrapper for full license details.

    ClapAUv3AudioUnit is the AUAudioUnit subclass that wraps a CLAP plugin as an AUv3 Audio Unit.
*/

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnullability-completeness"

#import <AudioToolbox/AudioToolbox.h>
#import <AVFoundation/AVFoundation.h>
#import <CoreAudioKit/CoreAudioKit.h>
#import <CoreAudioKit/AUViewController.h>
#import <CoreMIDI/CoreMIDI.h>

#import "auv3_platform.h"

#include <clapwrapper/chardio-auv3-metadata.h>

#include <string>
#include <vector>

#pragma clang diagnostic pop

@class ClapAUv3AudioUnit;

namespace Clap::AUv3
{
bool inputNotePortsSupportMIDI2(const clap_plugin_t *plugin,
                                const clap_plugin_note_ports_t *notePorts);
NSTimeInterval tailTimeForSamples(uint32_t samples, double sampleRate) noexcept;

// Chardio's optional metadata table is deliberately consumed only by the
// non-realtime AU lifecycle. The fallback declaration bundled with
// clap-wrapper predates these fields, so an ordinary standalone wrapper build
// continues to expose no Chardio-specific runtime policy.
#if defined(CLAP_WRAPPER_HAS_CHARDIO_AUV3_METADATA)
struct ChardioFactoryPreset
{
  int32_t number = 0;
  std::string name;
};

struct ChardioViewConfiguration
{
  uint32_t minimumWidth = 0;
  uint32_t minimumHeight = 0;
  chardio_auv3_view_policy_t policy = CHARDIO_AUV3_VIEW_POLICY_HOST_DEFAULT;
};

class ChardioRuntimeMetadata
{
 public:
  ChardioRuntimeMetadata() = default;
  static ChardioRuntimeMetadata find(const clap_plugin_t *plugin);

  bool prepareForAUv3(const clap_plugin_t *plugin) const;
  std::vector<ChardioFactoryPreset> factoryPresets(const clap_plugin_t *plugin) const;
  bool loadFactoryPreset(const clap_plugin_t *plugin, int32_t number) const;
  bool getViewConfiguration(const clap_plugin_t *plugin, ChardioViewConfiguration &result) const;
  bool supportsMPE(const clap_plugin_t *plugin) const;

 private:
  explicit ChardioRuntimeMetadata(const chardio_plugin_auv3_metadata_t *metadata) : _metadata(metadata) {}

  const chardio_plugin_auv3_metadata_t *_metadata = nullptr;
};
#else
class ChardioRuntimeMetadata
{
 public:
  static ChardioRuntimeMetadata find(const clap_plugin_t *) { return {}; }
  bool prepareForAUv3(const clap_plugin_t *) const { return true; }
  bool loadFactoryPreset(const clap_plugin_t *, int32_t) const { return false; }
  bool supportsMPE(const clap_plugin_t *) const { return false; }
};
#endif
}  // namespace Clap::AUv3

// The view controller is also the AUAudioUnitFactory.
// Apple's AUv3 model requires the NSExtensionPrincipalClass to be the
// AUViewController subclass which also conforms to AUAudioUnitFactory.
@interface ClapAUv3ViewController : AUViewController <AUAudioUnitFactory>
@property(nonatomic, strong) ClapAUv3AudioUnit *audioUnit;
// Subclasses (generated by build-helper) override this to provide plugin-specific info
- (AUAudioUnit *)createAudioUnitWithComponentDescription:(AudioComponentDescription)desc
                                                   error:(NSError **)error;
@end

@interface ClapAUv3AudioUnit : AUAudioUnit
{
 @package
  // Weak back-reference to the factory VC that created this AU.
  // Set by [ClapAUv3ViewController setAudioUnit:] during factory creation.
  // Used by requestViewControllerWithCompletionHandler: so the host can
  // obtain the VC for displaying the plugin's custom UI.
  __weak ClapAUv3ViewController *_factoryViewController;
}

- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError **)outError
                                    clapName:(NSString *)clapName
                                      clapId:(NSString *)clapId
                                   clapIndex:(int)clapIndex;

// Called by the view controller to create/attach the CLAP GUI to a parent view.
// Returns YES if the CLAP plugin has a GUI and it was successfully created.
// parentView is an NSView on macOS and a UIView on iOS (see auv3_platform.h).
- (BOOL)createGUIInView:(CLAPWRAP_ViewClass *)parentView
                  width:(uint32_t *)outWidth
                 height:(uint32_t *)outHeight;

// Called by the view controller when the view is being torn down.
- (void)destroyGUI;

// Called by the view controller to check if the CLAP GUI supports resizing.
- (BOOL)canResizeGUI;

// Called by the view controller when the host resizes the view.
- (BOOL)setGUISize:(uint32_t)width height:(uint32_t)height;

// Called by the view controller to establish the back-reference needed
// for gui_request_resize to set preferredContentSize on the VC.
- (void)setViewController:(ClapAUv3ViewController *)vc;

// Retrieves cached Chardio view policy. No plug-in callback is made here.
- (BOOL)getViewPolicy:(uint32_t *)outPolicy
          minimumWidth:(uint32_t *)outMinimumWidth
         minimumHeight:(uint32_t *)outMinimumHeight;

@end
